# To run locally
# npx @techdocs/cli serve -v -c ./mkdocs.yml
# 
site_name: 'awesome-k6 Internal Documentation'
repo_url: https://github.com/grafana/awesome-k6
edit_uri: edit/main/docs

theme:
  name: material
  features:
    - navigation.sections

plugins:
  - techdocs-core
