name: Awesome Lint

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  Awesome_Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 20
      - name: Run Awesome Lint
        run: npx -y awesome-lint README.md
      - name: Run link check
        uses: gaurav-nelson/github-action-markdown-link-check@5c5dfc0ac2e225883c0e5f03a85311ec2830d368 # v1
        with:
          use-quiet-mode: 'no'
          use-verbose-mode: 'yes'