name: Awesome Lint

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  Awesome_Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run Awesome Lint
        run: npx -y awesome-lint README.md
      - name: Run link check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'no'
          use-verbose-mode: 'yes'